### ISSUE TITLE
Fontsize not changing font size

### ISSUE THREAD

**Issue by masterwishx** [little-brother/csvtab-wlx#1]
How to change font size to bigger fonts ?
Font size in file not changing fontsize in cudalister

**Comment by little-brother** [comment]
Are you try to use `Ctrl` + Mouse wheel or [set](https://github.com/little-brother/csvtab-wlx/wiki#settings) `font-size = 70` for `[csvtab]`-section?

**Comment by little-brother** [comment]
No answer.

**Comment by masterwishx** [comment]
> Are you try to use `Ctrl` + Mouse wheel or [set](https://github.com/little-brother/csvtab-wlx/wiki#settings) `font-size = 70` for `[csvtab]`-section?

i tryed changing in config  file fontsize , ctrl +mouse is working

**Comment by little-brother** [comment]
Could ypu provide more details?
Version TC/OS (+bit). Are you using `csvtab.ini` or `lsplugin.ini`?

**Comment by masterwishx** [comment]
Tc 10 64bit, windows 1809 ltsc, csvtab.ini

**Comment by little-brother** [comment]
If you increase font size by mousewheel, close lister and then reopen file. Do the font-size still big or as default?

**Comment by masterwishx** [comment]
Yes it's save font size by mousewhell after reopen
But I didn't know this option for increase fonts when opened issue

**Comment by little-brother** [comment]
I mean that if the font size is saved then TC uses `font-size` from ini. But it looks like you edit an another ini file.

**Comment by masterwishx** [comment]
I will check it again...
But from I remember I was edit ini file csvtab.ini
That in plugins after csvtab installed...

**Comment by little-brother** [comment]
I think it was misunderstanding. Please open this issue again, if it's a bug.

**Comment by masterwishx** [comment]
I checked I think I was edit defaults.ini file in tc/plugins/wlx/csvtab
And after I change font size with ctrl+mouse wheel, fontsize=16 is still in this file.

But it's not a problem anymore, unless I can change fontsize by ctrl+mouse.
