### ISSUE TITLE
After the csv exceeds 128 columns, the data will be displayed in the second row. How to solve it?

### ISSUE THREAD

**Issue by gdqb521** [little-brother/csvtab-wlx#2]
After the csv exceeds 128 columns, the data will be displayed in the second row. How to solve it?

**Comment by little-brother** [comment]
Yes it's a bug. The maximum column count is 128 because Windows component that using for grid is slow down for each new column. With 200+ columns it will be almost stopped. 

The fix can be to reject 129 and next columns and their data. So you will not see all data.

**Comment by little-brother** [comment]
Fixed.
