### ISSUE TITLE
Разделители

### ISSUE THREAD

**Issue by raddyst** [little-brother/csvtab-wlx#4]
Добрый, всё-таки хотелось бы иметь возможность назначать разделитель по умолчанию., плагин в основном используется для просмотра простеньких отчётов с crystaldiskinfo, и при содержимом 
`2023/11/20 15:39:14,110` 
разделителем на автомате становится двоеточие, вместо запятой.
![image](https://github.com/little-brother/csvtab-wlx/assets/8584929/34f721cc-2f33-49c2-868f-9548331ac6e4)

[01.csv](https://github.com/little-brother/csvtab-wlx/files/13429994/01.csv)

**Comment by little-brother** [comment]
Done. Use `default-column-delimiter=,`.
P.S. The dark mode is better with `disable-grid-lines = 1`.
