### ISSUE TITLE
crashes (incl. TC) when sorting or filtering large file

### ISSUE THREAD

**Issue by adoeller** [little-brother/csvtab-wlx#5]
[users_data.zip](https://github.com/little-brother/csvtab-wlx/files/14050405/users_data.zip)

sorting country or state works, sorting city crashes.

**Comment by little-brother** [comment]
Thanks for the report. The cause is bad formatted strings, not size e.g.
```
4500876,DS3LIP,Daihyun ,Daihyun,   ,Gyeonggi Province,Suedkorea
```
I'll try to fix the csv-parser soon.

**Comment by little-brother** [comment]
Done. It was easier than I thought.
