### ISSUE TITLE
feature - optional/toggle CSV header

### ISSUE THREAD

**Issue by jelinj8** [little-brother/csvtab-wlx#6]
For CSV files with no header it would be nice to be abble to switch off loading first line as header, when it contains data.

**Comment by little-brother** [comment]
Do you mean this?

![изображение](https://github.com/little-brother/csvtab-wlx/assets/20204037/f7946769-cd44-4330-9d81-98c3b03899c0)

**Comment by jelinj8** [comment]
Yes, exactly - did not find it, thanks (it seems I'm not the only one...).
