### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by tec-leo** [little-brother/csvtab-wlx#8]
Text size is rather small on high dpi monitors.
Is it possible to automatically scale it with system settings or depending on total commander settings (or any other way) ?

thank you for the plugin

**Comment by little-brother** [comment]
Please check the next version [csvtab-1.0.8a.zip](https://github.com/little-brother/csvtab-wlx/files/14872893/csvtab-1.0.8a.zip) with
`dpi-aware = 1` in ini-file. Does it solve the issue?

P.S. I don't have hiDPI display, so I can't verify it myself.

**Comment by tec-leo** [comment]
Unfortunately not, also a restart of Total commander did not help.
but thanks for the quick response.

**Comment by little-brother** [comment]
The text is small even if you changed the size by `Ctrl + MouseWheel` or `font-size` in ini?
Could you provide a screenshot?

**Comment by tec-leo** [comment]
I tried again and font-size setting as well as Ctrl + MouseWheel works.
Thank you very much.
I think the issue can be closed.
