### ISSUE TITLE
fit content to cell

### ISSUE THREAD

**Issue by Alexisback** [little-brother/csvtab-wlx#9]
is it possible to adapt the content to the cell?
that is, horizontally enlarge the auto cells based on the content

**Comment by little-brother** [comment]
The plugin already does it. Maybe you should to increase `max-column-width` (by default is 300px) in `csvtab.ini`.
If `max-column-width` doesn't solve the issue, could you provide an image with current and desire widths?

P.S. If you mean to show a long text as multiline then is not possible due WinAPI control limitations.
